export const CategoryList=[
    {id:1,
    img:'/assets/img/category.png',
    title:'CLOTHES',
    cat:'clothes'
    },
    {id:1,
        img:'/assets/img/carcategory.png',
        title:'CARS',
        cat:'Cars'
        },
        {id:1,
            img:'/assets/img/nikeshoescategory.png',
            title:'SHOES',
            cat:'Shoes'
            },
            {id:1,
                img:'/assets/img/watchcategory.png',
                title:'WATCHES',
                cat:'Watches'
                },
];